device: cuda:2
experiment_name: MixtureMemory

seed: 0
__set_seed: !apply:torch.manual_seed [!ref <seed>]

skip_test: False

# Data preparation
train_locales: [conflict, nature, movement, scenario, animal, talk, human]
hybrid_locales: [conflict_nature, movement_nature, scenario_animal, talk_human]
test_locales: [conflict, nature, movement, scenario, animal, talk, human, conflict_nature, movement_nature, scenario_animal, talk_human]
hybrid_replay_ratio: 1.0
data_name: Speech-join
data_folder: !ref /data1/kjq2/workplace/ContinualSpeechEE/data/<data_name>
max_durations: [80000, 30000, 30000]  # Maximum total durations in seconds for train, dev, and test splits for each locale

# Output directories
result_folder: /data1/kjq2/workplace/ContinualSpeechEE/results
dir_name: epochs=<num_epochs>_expert=<expert_type>_tok=<num_experts_per_tok>_replay_ratio=<hybrid_replay_ratio>_gateLoss=<gate_loss_type>_router_aux_loss_coef=<router_aux_loss_coef>
output_folder: !ref <result_folder>/<data_name>/<whisper_variant>/<experiment_name>/<seed>/<dir_name>
save_folder: !ref <output_folder>/save

# Training parameters
train_batch_size: 16
valid_batch_size: 32
train_num_workers: 6
valid_num_workers: 6

sample_rate: 16000
sorting: ascending
avoid_if_longer_than: 20  # Remove utterances longer than 10s (open microphones)

ignore_index: -100  # For cross-entropy loss
label_smoothing: 0

num_epochs: 2
lr: 0.0001
improvement_threshold: 0.0025
annealing_factor: 0.8

#whisper_variant: whisper-large-v2
whisper_variant: whisper-base
encoder_only: False
freeze: False
freeze_encoder: True
adapter_hidden_dim: 32
expert_type: Adapter  # Can be Top2MLP, Adapter
num_experts_per_tok: 1
gate_loss_type: last # Can be last, or sum
#router_aux_loss_coef: 0.01
router_aux_loss_coef: 0
num_new_decoder_layers: 1

max_target_length: 448  # Must be <= 448 (Whisper maximum target length)
nonfinite_patience: 10
max_grad_norm: 5.0
auto_mix_prec: True
gradient_checkpointing: False
ckpt_interval_minutes: 600

max_gen_tokens: 80
forced_decoder_locale: null  # Set dynamically
normalize_transcripts: False

# Dataloader options
train_dataloader_kwargs:
    batch_size: !ref <train_batch_size>
    num_workers: !ref <train_num_workers>

valid_dataloader_kwargs:
    batch_size: !ref <valid_batch_size>
    num_workers: !ref <valid_num_workers>

# Modules
whisper: !new:model.WhisperMoeV3
    source: !ref openai/<whisper_variant>
    save_path: !ref <save_folder>/checkpoint
    sampling_rate: !ref <sample_rate>
    encoder_only: !ref <encoder_only>
    freeze: !ref <freeze>
    freeze_encoder: !ref <freeze_encoder>
    gate_loss_type:  !ref <gate_loss_type>
    router_aux_loss_coef:  !ref <router_aux_loss_coef>

ce_loss: !new:torch.nn.CrossEntropyLoss
    ignore_index: !ref <ignore_index>
    label_smoothing: !ref <label_smoothing>

modules:
    whisper: !ref <whisper>

# Optimizers
opt_class: !name:torch.optim.AdamW
    lr: !ref <lr>

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: !ref <improvement_threshold>
    annealing_factor: !ref <annealing_factor>
    patient: 0

# Performance metrics
wer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    split_tokens: True
acc_computer:  !name:speechbrain.utils.metric_stats.ClassificationStats
# Counters, checkpointers, loggers, etc.
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <num_epochs>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <whisper>
        scheduler: !ref <lr_annealing>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <output_folder>/<experiment_name>.txt
